name = "tiny-webauthn-example-app"
main = "src/worker.ts"
compatibility_date = "2023-09-17"
routes = [
  { pattern = "webauthn.levischuck.com", zone_name = "levischuck.com", custom_domain = true }
]

[vars]
RP_ID = "levischuck.com"
ORIGINS = "[\"https://webauthn.levischuck.com\",\"https://levischuck.com\"]"

[[kv_namespaces]]
binding = "WEBAUTHN_DEMO"
id = "fb57935cae5d4a1aa1f35a77caad6a79"
preview_id = "fb57935cae5d4a1aa1f35a77caad6a79"

[site]
bucket = "./static"
